### ISSUE TITLE
Available on AUR?

### ISSUE THREAD

**Issue by uwla** [arcanericky/ga-cmd#41]
HI, thanks for the project, it is really awesome!

It seems like this project is not available on AUR (Arch User Repository), at least I did not find it searching with yay or pacman. It would be good to publish it, isn't?

**Comment by arcanericky** [comment]
While you're more than welcome to publish it, you should consider using and publishing my TOTP utility written in Go that's at https://github.com/arcanericky/totp. It has many improvements, especially from a usability standpoint. Among them are:

- Executables for Linux, Windows, and Macintosh (more on request)
- Support for multiple secrets
- Command line options to add, delete, update, rename, and list secrets
- No more manual editing of a configuration file
- Ad-hoc secret support
- Bash completion
- Specify the time used to generate the seed, and/or adjust the current time forward and backward
- Continuous code output every 30 seconds
- Streaming of a shared secret collection using stdio

Keep in mind this `ga-cmd` project uses the Google Authenticator PAM Module source to perform the heavy lifting. I'm unsure what the licensing of that is, so you'll want to check on that before publishing.

If you use my TOTP utility written in Go (above) instead, you'll steer clear of any licensing issues.

**Comment by uwla** [comment]
Ok thanks! Indeed, I liked the other project more than this
