### ISSUE TITLE
import existing codes?

### ISSUE THREAD

**Issue by BustedSec** [arcanericky/ga-cmd#42]
is there a mechanism to import existing codes from the Google Authenticator android app? It can export them but I don't see how to import them into this. 

Thanks!

**Comment by arcanericky** [comment]
First, if you're using this as an end user and not for learning and reference, you should be using [my TOTP project](https://github.com/arcanericky/totp) instead.

Then to answer your question. There's not a way to directly import them into this. This code is not aware of Google Authenticator or the format of its exported data. If you can read through the exported data to find the code and enter or configure them, you can try that way. However, I'm unfamiliar with this exported data so don't know if this is possible either.
