### ISSUE TITLE
Package for MacOS M1/M2

### ISSUE THREAD

**Issue by matanbaruch** [arcanericky/ga-cmd#44]
Hey,
Can you please compile this for M1/M2? 
I tried building from source and got an error

```
src ./build.sh
Building without internal key
rm -rf bin
rm -f *.o config.h *.gcno *.gcda *.gcov coverage*.html
(cd google-authenticator-libpam && make clean)
make[1]: *** No rule to make target `clean'.  Stop.
make: *** [clean] Error 2
```

**Comment by arcanericky** [comment]
I don't have a macOS system of any type to compile this. I also don't really support this - it's just here for historical reference. Check out the README for this project - it points you to a more supported project that's better and does support MacOS M1/M2. From the README...

> If you're using this repository for the compiled releases to generate TOTP codes you should instead be using [my TOTP utility](https://github.com/arcanericky/totp) written in Go. It offers too many improvements to be overlooked and is the utility I personally use. Among these are:
> 
> - Executables for Linux, Windows, and Macintosh (more on request)
> - Support for multiple secrets
> - Command line options to add, delete, update, rename, and list secrets
> - No more manual editing of a configuration file
> - Ad-hoc secret support
> - Bash completion
> - Specify the time used to generate the seed, and/or adjust the current time forward and backward
> - Continuous code output every 30 seconds
> - Streaming of a shared secret collection using stdio
> 
> My [TOTP project on GitHub](https://github.com/arcanericky/totp).
