### ISSUE TITLE
Secrets larger than 16 characters?

### ISSUE THREAD

**Issue by gboudreau** [arcanericky/ga-cmd#5]
Do you know how I should use secrets that are longer than 16 characters?
In my Google Authenticate sqlite3 database, I see some 16 characters secrets (Facebook, GitHub, Heroku), but other secrets are longer, namely Dropbox (26 characters), Google (32 characters) and Amazon AWS (64 characters).
How can I compile a ga-cmd that would use those secrets?

Thanks.

**Comment by Poil** [comment]
Same problem here =)

**Comment by davama** [comment]
Same here. When use official 
https://github.com/google/google-authenticator-libpam
