### ISSUE TITLE
Problem with build on Cygwin

### ISSUE THREAD

**Issue by lcfonseca** [arcanericky/ga-cmd#6]
I'm trying to build on Cygwin and there is some problem.

$ ./build.sh ZAYNP7CBZB2FQNFF
git pull
gcc -c -std=gnu99 google-authenticator/libpam/hmac.c
makefile:13: recipe for target 'hmac.o' failed
make: **\* [hmac.o] Error 1

**Comment by arcanericky** [comment]
I don't use or build on Cygwin but if someone wants to get it working on Cygwin I'll be happy to take a pull request for it.

If there's more detail in the error I can give suggestions on it.

This issue is almost 5 years old now. Closing it.
