### ISSUE TITLE
Multiple Google Auth Accounts

### ISSUE THREAD

**Issue by davama** [arcanericky/ga-cmd#9]
Hello,
This is a very cool tool. 
I tried using it with multiple accounts by creating different folders
~/ga-cmd-acc1/src/bin/ga-cmd
~/ga-cmd-acc2/src/bin/ga-cmd
~/ga-cmd-acc3/src/bin/ga-cmd

I followed your how-to on each. Unfortunately only the 1st one was giving me a correct 6 digit code. Is this possible?

Thanks
Dave

**Comment by dR3b** [comment]
I rename the file "ga-cmd" to e.g. "ga-github-X" and move it to "~/bin". Then I delete the "bin" directory and compile a new version if necessary.

**Comment by arcanericky** [comment]
Closing because this is a duplicate of #8
